name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Run tests
        run: go test ./... -cover

  style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Format files
        run: test -z $(go fmt ./...)

      - name: Install staticcheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH  # Add the go bin to the PATH

      - name: Linter check
        run: staticcheck ./...
